version: '3'
services:
  nginx:
    image: nginx:1.19.2
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./templates:/etc/nginx/templates/
      - './ssl:/ssl/'
    depends_on:
      - evides
      - resview
    networks:
      - evidssnet 
    environment:
      - EVIDSSDOCS_IP=$EVIDSSDOCS_IP
      - EVIDES_IP=$EVIDES_IP
      - RESVIEW_IP=$RESVIEW_IP
      - REDASH_IP=$REDASH_IP
      - EVIDSS_DOMAINNAME=$EVIDSS_DOMAINNAME
      - EVIDES_PORT=$EVIDES_PORT
      - RESVIEW_PORT=$RESVIEW_PORT
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://${MAIN_HOST}:${MAIN_PORT}/${MAIN_DB} -schemas=public -user=${DBWRITE_USER} -password=${DBWRITE_PWD} migrate
    volumes:
      - ./database/migrations:/flyway/sql
    networks:
      - evidssnet
  #  network_mode: host    
  evides:
    build: './evides'
    ports:
      - '${EVIDES_PORT}:${EVIDES_PORT}'
    networks:
      - evidssnet
    environment:
      - GITHUB_PAT=$GITHUB_PAT
      - EVIDES_PORT=$EVIDES_PORT
      - AUTH0_USER=$AUTH0_USER
      - AUTH0_KEY=$AUTH0_KEY
      - AUTH0_SECRET=$AUTH0_SECRET
      - AFDC_API_KEY=$AFDC_API_KEY
      - MAPBOX_ACCESS_TOKEN=$MAPBOX_ACCESS_TOKEN
      - MAIN_USER=$DBWRITE_USER
      - MAIN_PWD=$DBWRITE_PWD
      - MAIN_HOST=$MAIN_HOST
      - MAIN_PORT=$MAIN_PORT
      - MAIN_DB=$MAIN_DB
    restart: always
  resview:
    build: './resview'
    ports:
      - '${RESVIEW_PORT}:${RESVIEW_PORT}'
    networks:
      - evidssnet
    environment:
      - GITHUB_PAT=$GITHUB_PAT
      - RESVIEW_PORT=$RESVIEW_PORT
      - AFDC_API_KEY=$AFDC_API_KEY
      - MAPBOX_ACCESS_TOKEN=$MAPBOX_ACCESS_TOKEN
      - MAIN_USER=$DBREAD_USER
      - MAIN_PWD=$DBREAD_PWD
      - MAIN_HOST=$MAIN_HOST
      - MAIN_PORT=$MAIN_PORT
      - MAIN_DB=$MAIN_DB
    restart: always
  tripgen:
    build: './tripgen'
    networks:
      - evidssnet
    environment:
      - GITHUB_PAT=$GITHUB_PAT
      - AFDC_API_KEY=$AFDC_API_KEY
      - MAPBOX_ACCESS_TOKEN=$MAPBOX_ACCESS_TOKEN
      - MAIN_USER=$DBREAD_USER
      - MAIN_PWD=$DBREAD_PWD
      - MAIN_HOST=$MAIN_HOST
      - MAIN_PORT=$MAIN_PORT
      - MAIN_DB=$MAIN_DB
      - SOCRATA_APP_TOKEN=$SOCRATA_APP_TOKEN
      - MAILGUN_API_KEY=$MAILGUN_API_KEY
  redis:
    image: 'redis:6.0.6'
    volumes:
      - $PWD/redis-data:/var/lib/redis
    ports:
      - '6379:6379'
    networks:
      - evidssnet
    restart: always
  simman:
    build: './simman'
    depends_on:
      - redis
    ports:
      - '${SIMMAN_PORT}:${SIMMAN_PORT}'
    networks:
      - evidssnet
    volumes:
      - $HOME/.aws/:/home/app/.aws/:ro
    environment:
      - SIMMAN_PORT=$SIMMAN_PORT
      - REDIS_HOST=$REDIS_HOST
      - MAIN_USER=$DBWRITE_USER
      - MAIN_PWD=$DBWRITE_PWD
      - MAIN_HOST=$MAIN_HOST
      - MAIN_PORT=$MAIN_PORT
      - MAIN_DB=$MAIN_DB
      - EC2_SECURITY_GROUPNAME=$EC2_SECURITY_GROUPNAME
      - EC2_KEYPAIR_NAME=$EC2_KEYPAIR_NAME
      - EC_R_AMI_ID=$EC_R_AMI_ID
      - IAM_INSTANCE_PROFILE_ARN=$IAM_INSTANCE_PROFILE_ARN
      - EC_GAMA_AMI_ID=$EC_GAMA_AMI_ID
      - RESVIEW_HOST=$RESVIEW_HOST
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
    command:
      - nodemon
      - index.js
    restart: always

networks:
  evidssnet: null
